export const ErrorCodes = {
    // Auth Errors
    AUTH_OTP_INVALID: "AUTH_OTP_INVALID",
    AUTH_OTP_EXPIRED: "AUTH_OTP_EXPIRED",
    AUTH_OTP_RATE_LIMITED: "AUTH_OTP_RATE_LIMITED",
    AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
    AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
    AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
    AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",

    // User Errors
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_SUSPENDED: "USER_SUSPENDED",
    USER_INACTIVE: "USER_INACTIVE",
    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",

    // Validation Errors
    VALIDATION_ERROR: "VALIDATION_ERROR",
    INVALID_INPUT: "INVALID_INPUT",

    // Resource Errors
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

    // Address Errors
    ADDRESS_NOT_SERVICEABLE: "ADDRESS_NOT_SERVICEABLE",

    // Retailer Errors
    RETAILER_NOT_FOUND: "RETAILER_NOT_FOUND",
    RETAILER_NOT_APPROVED: "RETAILER_NOT_APPROVED",

    // Product Errors
    PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
    OUT_OF_STOCK: "OUT_OF_STOCK",

    // Cart Errors
    CART_EMPTY: "CART_EMPTY",
    CART_RETAILER_MISMATCH: "CART_RETAILER_MISMATCH",

    // Order Errors
    ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
    ORDER_INVALID_STATE: "ORDER_INVALID_STATE",
    ORDER_CANCEL_NOT_ALLOWED: "ORDER_CANCEL_NOT_ALLOWED",

    // Delivery Errors
    DELIVERY_NOT_AVAILABLE: "DELIVERY_NOT_AVAILABLE",
    DELIVERY_PARTNER_NOT_FOUND: "DELIVERY_PARTNER_NOT_FOUND",
    DELIVERY_PARTNER_UNAVAILABLE: "DELIVERY_PARTNER_UNAVAILABLE",
    ASSIGNMENT_CONFLICT: "ASSIGNMENT_CONFLICT",
    ASSIGNMENT_NOT_FOUND: "ASSIGNMENT_NOT_FOUND",

    // Payment Errors
    PAYMENT_INVALID: "PAYMENT_INVALID",
    PAYMENT_FAILED: "PAYMENT_FAILED",

    // Admin Errors
    ADMIN_ACCESS_DENIED: "ADMIN_ACCESS_DENIED",

    // System Errors
    INTERNAL_ERROR: "INTERNAL_ERROR",
    DATABASE_ERROR: "DATABASE_ERROR",
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
    IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT"
} as const;

export type ErrorCodeType = typeof ErrorCodes[keyof typeof ErrorCodes];
